version: '3'
services:
  # common
  mysql:
    image: mysql:5.7
    volumes:
      - "./mysql/data:/var/lib/mysql"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4'
    environment:
      - MYSQL_ROOT_PASSWORD=MjqVXTUhDgp4xsakiwT5
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"
  memcached:
    image: memcached
  reverse_proxy_nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./reverse_proxy_nginx/conf.d:/etc/nginx/conf.d"
      - "./reverse_proxy_nginx/cert:/cert"


  # xbxbwiki
  xbxb_phpfpm:
    image: luminisward/mw-php:7.3
    # build: ./php
    volumes:
      - "./php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "./php/php.ini:/usr/local/etc/php/php.ini"
      - "./mediawiki:/var/www/html"
      - "./xbxb/LocalSettings.php:/var/www/html/LocalSettings.php"
      - "./xbxb/images:/var/www/html/images"
    # Xdebug
    # extra_hosts:
    #   docker_host: 192.168.66.12
  xbxb_nginx:
    image: nginx:latest
    # ports:
    #   - "8080:8080"
    volumes:
      - "./xbxb/nginx/conf.d:/etc/nginx/conf.d"
      - "./mediawiki:/var/www/html"
      - "./xbxb/LocalSettings.php:/var/www/html/LocalSettings.php"
      - "./xbxb/images:/var/www/html/images"

  # xbdwiki
  xbd_phpfpm:
    image: luminisward/mw-php:7.3
    # build: ./php
    volumes:
      - "./php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "./php/php.ini:/usr/local/etc/php/php.ini"
      - "./mediawiki:/var/www/html"
      - "./xbd/LocalSettings.php:/var/www/html/LocalSettings.php"
      - "./xbd/images:/var/www/html/images"
    # Xdebug
    # extra_hosts:
    #   docker_host: 192.168.66.12
  xbd_nginx:
    image: nginx:latest
    # ports:
    #   - "8080:8080"
    volumes:
      - "./xbd/nginx/conf.d:/etc/nginx/conf.d"
      - "./mediawiki:/var/www/html"
      - "./xbd/LocalSettings.php:/var/www/html/LocalSettings.php"
      - "./xbd/images:/var/www/html/images"
