version: '3'
services:
  phpfpm:
    image: luminisward/mw-php
    volumes:
      - "./php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "./php/php.ini:/usr/local/etc/php/php.ini"
      - "./mediawiki:/var/www/html"
    # Xdebug
    # extra_hosts:
    #   docker_host: 192.168.66.10 
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./mediawiki:/var/www/html"

  mysql:
    image: mysql:5.7.23
    volumes:
      - "mysql:/var/lib/mysql"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4'
    environment:
      - MYSQL_ROOT_PASSWORD=MjqVXTUhDgp4xsakiwT5
      - TZ=Asia/Shanghai

  parsoid:
    image: rlewkowicz/parsoid:latest
    # ports:
    #   - "8000:8000"
    volumes:
      - "./parsoid/config.yaml:/usr/local/lib/node_modules/parsoid/config.yaml"
    hostname: parsoid
      
  restbase:
    image: wikitolearn/restbase
    # ports:
    #   - "7231:7231"
    volumes:
      - "./restbase/config.yaml:/opt/config.yaml:ro"

  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql

  memcached:
    image: memcached

volumes:
  mysql:
