version: '3'
services:
  phpfpm:
    image: luminisward/mw-php
    # build: ./php
    volumes:
      - "./php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "./php/php.ini:/usr/local/etc/php/php.ini"
      - "./mediawiki:/var/www/html"
    # Xdebug
    # extra_hosts:
    #   docker_host: 192.168.66.10 

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./mediawiki:/var/www/html"

  mysql:
    image: mysql:5.7
    volumes:
      - "mysql:/var/lib/mysql"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4'
    environment:
      - MYSQL_ROOT_PASSWORD=MjqVXTUhDgp4xsakiwT5
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"

  parsoid:
    image: thenets/parsoid:0.10.0
    environment:
      - PARSOID_DOMAIN_api=http://nginx/api.php
    # ports:
    #   - "8000:8000"
    hostname: parsoid
      
  restbase:
    image: wikitolearn/restbase
    # ports:
    #   - "7231:7231"
    volumes:
      - "./restbase/config.yaml:/opt/config.yaml:ro"

  memcached:
    image: memcached

  # myadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - PMA_HOST=mysql

volumes:
  mysql:
