<?php
# This file was automatically generated by the MediaWiki 1.31.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

# Set environment
$environment = "development";
// $environment = "production";

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "乐园数据管理室";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";
$wgArticlePath = '/$1';

## The protocol and server name to use in fully-qualified URLs
if ($environment == "development") {
  $host = $_SERVER['HTTP_X_FORWARDED_HOST'] ? $_SERVER['HTTP_X_FORWARDED_HOST'] : $_SERVER["HTTP_HOST"];
  $wgServer = "http://".$host;
} elseif ($environment == "production") {
  $wgServer = "https://xenoblade2.cn";
  $wgSecureLogin = true;
  //$wgLoadScript = "//loader.xenoblade2.cn/load.php";
  $hour = intval(date("H"));
  //header("HourP: $hour");
  if ($hour >= 2 && $hour < 23) {
    $wgUploadPath = "//loader.xenoblade2.cn/images";
  }
  $wgCookieDomain = ".xenoblade2.cn";
}

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
#$wgLogo = "$wgResourceBasePath/resources/assets/wiki.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "monado@xenoblade.cn";
$wgPasswordSender = "monado@xenoblade.cn";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "mysql";
$wgDBname = "xbxbwiki";
$wgDBuser = "root";
if ($environment == "development") {
  $wgDBpassword = "MjqVXTUhDgp4xsakiwT5";
} elseif ($environment == "production") {
  $wgDBpassword = "Vd4y5b3tvQwU2FbvVWMu";
}

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
if ($environment == 'production') {
  $wgMainCacheType = CACHE_MEMCACHED;
  $wgMemCachedServers = [ 'memcached:11211' ];
}

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "C.UTF-8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "zh-hans";

$wgSecretKey = "3708be959954c3f88055b2dc58570bdf6290beec01f8b74338602d93476d47c6";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "4559268e8e6876f8";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "https://creativecommons.org/licenses/by-sa/4.0/";
$wgRightsText = "知识共享署名-相同方式共享";
$wgRightsIcon = "$wgResourceBasePath/resources/assets/licenses/cc-by-sa.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['*']['comment'] = false;
$wgGroupPermissions['user']['comment'] = true;
$wgGroupPermissions['sysop']['module-edit'] = true;
$wgGroupPermissions['sysop']['gadgets-edit'] = true;
$wgGroupPermissions['sysop']['gadgets-definition-edit'] = true;
$wgAddGroups['bureaucrat'][] = 'checkuser';
$wgRemoveGroups['bureaucrat'][] = 'checkuser';
$wgGroupPermissions['sysop']['mwoauthproposeconsumer'] = true;
$wgGroupPermissions['sysop']['mwoauthupdateownconsumer'] = true;
$wgGroupPermissions['sysop']['mwoauthmanageconsumer'] = true;
$wgGroupPermissions['sysop']['mwoauthsuppress'] = true;
$wgGroupPermissions['sysop']['mwoauthviewsuppressed'] = true;
$wgGroupPermissions['sysop']['mwoauthviewprivate'] = true;
$wgGroupPermissions['sysop']['mwoauthmanagemygrants'] = true;



$wgAvailableRights[] = 'module-edit';
$wgNamespaceProtection[828] = ['module-edit']; // MODULE 828
$wgHooks['ApiCheckCanExecute'][] = function($module, $user, &$message) {
  $moduleName = $module->getModuleName();
  if ($moduleName == 'scribunto-console' && !in_array('module-edit', $user->getRights())) {
    return false;
  }
  return true;
};

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "timeless";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'Timeless' );


# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtensions('ExtensionName');
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
wfLoadExtension( 'Avatar' );
wfLoadExtension( 'Cite' );
wfLoadExtension( 'CheckUser' );
wfLoadExtension( 'CodeEditor' );
wfLoadExtension( 'ConfirmEdit' );
// wfLoadExtension( 'Echo' );
//wfLoadExtension( 'FlowThread' );
wfLoadExtension( 'Gadgets' );
wfLoadExtension( 'Iframe' );
wfLoadExtension( 'ImageMap' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'Interwiki' );
wfLoadExtension( 'MsUpload' );
wfLoadExtension( 'MultimediaViewer' );
wfLoadExtension( 'OAuth' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'Poem' );
wfLoadExtension( 'ReplaceText' );
wfLoadExtension( 'Scribunto' );
wfLoadExtension( 'SemanticScribunto' );
wfLoadExtension( 'XBDBScribunto' );
wfLoadExtension( 'SpamBlacklist' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'TitleBlacklist' );
wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'WikiEditor' );
wfLoadExtension( 'EmbedVideo' );

# End of automatically generated settings.
# Add more configuration options below.

# Debug
$wgShowExceptionDetails = true;
$wgShowDBErrorBacktrace = true;

$wgLocaltimezone = "Asia/Shanghai";
$wgEmailConfirmToEdit = true;
$wgRateLimits['edit']['user'] = array( 30, 600 );
$wgUsePrivateIPs = true;
$wgSquidServersNoPurge = [
  "119.188.9.0/24",
  "42.236.93.0/24",
  "220.170.185.0/24",
  "115.231.186.0/25",
  "183.232.51.0/24",
  "61.182.137.0/25",
  "112.25.90.0/24",
  "59.51.81.128-191",
  "222.216.190.0/24",
  "122.190.2.0/24",
  "125.39.239.0/24",
  "183.61.177.0/24",
  "183.61.236.0/24",
  "124.95.168.128-191",
  "124.95.191.0/24",
  "58.211.2.0/24",
  "117.34.13.0/24",
  "150.138.150.0/24",
  "150.138.149.128/25",
  "157.255.25.0/24",
  "113.207.101.0/25",
  "111.32.135.0/25"
];
$wgCdnServers = $wgSquidServersNoPurge;
$wgArticleCountMethod = 'any';

# meta keywords and description
$wgHooks['OutputPageParserOutput'][] = function(OutputPage &$wgOut){
  $title = $wgOut->getPageTitle();
  $keywords = '异度神剑2,异度之刃2,Xenoblade2,ゼノブレイド２,专题,攻略,维基,wiki,MONOLITHSOFT,高橋哲哉,齋藤将嗣,光田康典,Nintendo Switch';
  if ($title == "首页") {
    $title = '';
    $wgOut->addMeta('description', '乐园数据管理室是一个由异度系列爱好者们打造的异度神剑2中文维基，专注于游戏内容的挖掘考据研究，让更多的玩家能了解异度系列的魅力，喜欢上尼娅，还有大家嗼' );
  } else {
    $keywords = $title . ',' . $keywords;
  }
  $keywords = str_replace(':', ',', $keywords);
  $keywords = str_replace('/', ',', $keywords);
  $wgOut->addMeta('keywords', $keywords );
};

# Google Analytics
if ($environment == "production") {
  $wgHooks['BeforePageDisplay'][] = function(OutputPage &$out){
    $out->addScript('<!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=UA-158633180-1"></script>');
    $out->addScript("<script>  window.dataLayer = window.dataLayer || [];  function gtag(){dataLayer.push(arguments);}  gtag('js', new Date());  gtag('config', 'UA-158633180-1');</script>");
  };
}

# footer links
$wgHooks['SkinTemplateOutputPageBeforeExec'][] = function( $sk, &$tpl ) {
  $tpl->set( 'qqgroup', $sk->footerLink( 'qqgroup', 'qqgrouppage' ) );
//  $tpl->data['footerlinks']['places'][] = 'qqgroup';
  $tpl->set( 'donate', $sk->footerLink( 'donate', 'donatepage' ) );
  $tpl->data['footerlinks']['places'][] = 'donate';
  unset($tpl->data['footerlinks']['info']);
  unset($tpl->data['privacy']);
  return true;
};

# 通知
$wgNotifyTypeAvailabilityByCategory = [
  'article-linked' => [
    'email' => false,
  ],
];

# 自动确认用户
$wgAutoConfirmAge = 3600 * 24 * 3; // days
$wgAutoConfirmCount = 0;

# 邮箱设置
if ($environment == "production") {
  $wgSMTP = [
    'host'     => 'ssl://smtp.qq.com',
    'IDHost'   => 'xenoblade2.cn',
    'port'     => '465',
    'auth'     => true,
    'username' => 'monado@xenoblade.cn',
    'password' => 'ybvrdzzhdgnhbhgj',
  ];
  $wgPasswordSender = 'monado@xenoblade.cn';
}

# Scribunto
$wgScribuntoDefaultEngine = 'luastandalone';
$wgScribuntoUseGeSHi = true;
$wgScribuntoUseCodeEditor = true;

# Gadgets
$wgGadgetsRepoClass = 'GadgetDefinitionNamespaceRepo';

# VisualEditor
$wgDefaultUserOptions['visualeditor-enable'] = 1;
$wgVirtualRestConfig['modules']['parsoid'] = array(
  // URL to the Parsoid instance
  // Use port 8142 if you use the Debian package
  'url' => 'http://xbxb_parsoid:8000',
  // // Parsoid "domain", see below (optional)
  'domain' => 'api',
  // // Parsoid "prefix", see below (optional)
  // 'prefix' => 'localhost'
);
$wgVirtualRestConfig['modules']['restbase'] = [
  'url' => "http://xbxb_restbase:7231",
  'domain' => 'api',
  'parsoidCompat' => false
];
$wgVisualEditorFullRestbaseURL = $wgServer .'/api/';
$wgVisualEditorAvailableNamespaces = [
  4 => true
];

# Avatar & Flowthread
$wgFlowThreadConfig['Avatar'] = $wgServer.'/extensions/Avatar/avatar.php?user=${username}';
$wgAvatarLogInRC = false;
$wgFlowThreadConfig['PopularPostCount'] = 0;

# Iframe
$wgIframe['server']['voice'] = [ 'scheme' => 'https', 'domain' => 'voice.xenoblade2.cn' ];
$wgIframe['server']['bilibili'] = [ 'scheme' => 'https', 'domain' => 'player.bilibili.com' ];

# MsUpload
$MSU_uploadsize = '1mb';

# NoTitle
require_once "$IP/extensions/NoTitle/NoTitle.php";
$wgRestrictDisplayTitle = false;

# XBXBScribunto
$wgXBDBScribuntoConnection["servername"]="192.168.66.12";
$wgXBDBScribuntoConnection["username"]="postgres";
$wgXBDBScribuntoConnection["password"]="123";
$wgXBDBScribuntoConnection["dbname"]='xb2';

# Extra Namespaces
$wgExtraNamespaces = [
  3000 => "物品",
  3001 => "物品讨论",
  3010 => "花的零件",
  3011 => "花的零件讨论",
  3100 => "敌人",
  3101 => "敌人讨论",
  3200 => "任务",
  3201 => "任务讨论",
  3300 => "佣兵团任务",
  3301 => "佣兵团任务讨论",
  3400 => "异刃",
  3401 => "异刃讨论",
  3500 => "牵绊对话",
  3501 => "牵绊对话讨论",
  3550 => "NPC",
  3551 => "NPC讨论",
  3600 => "商店",
  3601 => "商店讨论",
  3700 => "挑战战斗",
  3701 => "挑战战斗讨论",
  3800 => "武器",
  3801 => "武器讨论",
  3900 => "采集点",
  3901 => "采集点讨论",
  3910 => "宝箱",
  3911 => "宝箱讨论",
  3950 => "打捞点",
  3951 => "打捞点讨论",
  5000 => "黄金之国伊拉",
  5001 => "黄金之国伊拉讨论",
  5100 => "黄金之国物品",
  5101 => "黄金之国物品讨论",
  5200 => "黄金之国敌人",
  5201 => "黄金之国敌人讨论",
  5300 => "黄金之国任务",
  5301 => "黄金之国任务讨论",
  5400 => "黄金之国采集点",
  5401 => "黄金之国采集点讨论",
  5410 => "黄金之国宝箱",
  5411 => "黄金之国宝箱讨论",
  8000 => "FLAG",
  8001 => "FLAG talk",
  8888 => "JSON",
  8889 => "JSON talk"
  
];
$wgNamespaceAliases = [
  'item' => 3000,
  'enemy' => 3100,
  'quest' => 3200
];
$wgContentNamespaces[] = 3000;
$wgContentNamespaces[] = 3010;
$wgContentNamespaces[] = 3100;
$wgContentNamespaces[] = 3200;
$wgContentNamespaces[] = 3300;
$wgContentNamespaces[] = 3400;
$wgContentNamespaces[] = 3500;
$wgContentNamespaces[] = 3550;
$wgContentNamespaces[] = 3600;
$wgContentNamespaces[] = 3700;
$wgContentNamespaces[] = 3800;
$wgContentNamespaces[] = 3900;
$wgContentNamespaces[] = 3910;
$wgContentNamespaces[] = 3950;
$wgContentNamespaces[] = 5000;
$wgContentNamespaces[] = 5100;
$wgContentNamespaces[] = 5200;
$wgContentNamespaces[] = 5300;
$wgContentNamespaces[] = 5400;
$wgContentNamespaces[] = 5410;
$wgNamespacesToBeSearchedDefault[102] = false;
$wgNamespacesToBeSearchedDefault[108] = false;
$wgNamespacesToBeSearchedDefault[3000] = true;
$wgNamespacesToBeSearchedDefault[3010] = true;
$wgNamespacesToBeSearchedDefault[3100] = true;
$wgNamespacesToBeSearchedDefault[3200] = true;
$wgNamespacesToBeSearchedDefault[3300] = true;
$wgNamespacesToBeSearchedDefault[3400] = true;
$wgNamespacesToBeSearchedDefault[3500] = true;
$wgNamespacesToBeSearchedDefault[3550] = true;
$wgNamespacesToBeSearchedDefault[3600] = true;
$wgNamespacesToBeSearchedDefault[3700] = true;
$wgNamespacesToBeSearchedDefault[3800] = true;
$wgNamespacesToBeSearchedDefault[3900] = true;
$wgNamespacesToBeSearchedDefault[3910] = true;
$wgNamespacesToBeSearchedDefault[3950] = true;
$wgNamespacesToBeSearchedDefault[5000] = true;
$wgNamespacesToBeSearchedDefault[5100] = true;
$wgNamespacesToBeSearchedDefault[5200] = true;
$wgNamespacesToBeSearchedDefault[5300] = true;
$wgNamespacesToBeSearchedDefault[5400] = true;
$wgNamespacesToBeSearchedDefault[5410] = true;
$wgNamespacesWithSubpages[3400] = true;
$wgNamespacesWithSubpages[3200] = true;
$wgNamespacesWithSubpages[3700] = true;
$wgNamespacesWithSubpages[3900] = true;
$wgNamespacesWithSubpages[5000] = true;
$wgNamespacesWithSubpages[5300] = true;
$wgNamespacesWithSubpages[5400] = true;

$wgNamespacesWithSubpages[NS_MAIN] = true;
$wgNamespaceRobotPolicies[NS_TEMPLATE] = 'noindex';
$wgNamespaceContentModels[8888] = CONTENT_MODEL_JSON;

$wgNamespaceRobotPolicies[8000] = 'noindex';
$wgNamespaceRobotPolicies[8888] = 'noindex';

# SMW
$smwgNamespacesWithSemanticLinks[3000] = true;
$smwgNamespacesWithSemanticLinks[3010] = true;
$smwgNamespacesWithSemanticLinks[3100] = true;
$smwgNamespacesWithSemanticLinks[3200] = true;
$smwgNamespacesWithSemanticLinks[3300] = true;
$smwgNamespacesWithSemanticLinks[3400] = true;
$smwgNamespacesWithSemanticLinks[3500] = true;
$smwgNamespacesWithSemanticLinks[3550] = true;
$smwgNamespacesWithSemanticLinks[3600] = true;
$smwgNamespacesWithSemanticLinks[3700] = true;
$smwgNamespacesWithSemanticLinks[3800] = true;
$smwgNamespacesWithSemanticLinks[3900] = true;
$smwgNamespacesWithSemanticLinks[3910] = true;
$smwgNamespacesWithSemanticLinks[3950] = true;
$smwgNamespacesWithSemanticLinks[5000] = true;
$smwgNamespacesWithSemanticLinks[5100] = true;
$smwgNamespacesWithSemanticLinks[5200] = true;
$smwgNamespacesWithSemanticLinks[5300] = true;
$smwgNamespacesWithSemanticLinks[5400] = true;
$smwgNamespacesWithSemanticLinks[5410] = true;
enableSemantics( $wgServer );
$smwgPDefaultType = '_txt';
$smwgQMaxInlineLimit = 1000;
$wgNamespaceRobotPolicies[SMW_NS_PROPERTY] = 'noindex';
$wgNamespaceRobotPolicies[SMW_NS_CONCEPT] = 'noindex';
