language: php

matrix:
  fast_finish: true
  include:
    - env: DB=mysql; MW=REL1_27; TYPE=coverage
      php: 5.6
    - env: DB=mysql; MW=REL1_27;
      php: 5.6
    - env: DB=sqlite; MW=REL1_28; SITELANG=ja
      php: 5.6
    - env: DB=sqlite; MW=master; PHPUNIT=4.8.*
      php: 7.1
  allow_failures:
    # Use of UtfNormal::cleanUp was deprecated in MediaWiki 1.25.
    # [Called from ScribuntoHooks::invokeHook
    - env: DB=sqlite; MW=master; PHPUNIT=4.8.*

install:
  - bash ./tests/travis/install-mediawiki.sh
  - bash ./tests/travis/install-semantic-scribunto.sh

script:
  - bash ./tests/travis/run-tests.sh

after_success:
  - bash ./tests/travis/upload-coverage-report.sh

notifications:
  email:
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.composer/cache
